project:
  type: website
  output-dir: docs

website:
  title: "mofeed.xyz"
  site-url: "https://mofeed.xyz"
  description: "Technology, Data Science, AI, and everything in between"
  search: true
  cookie-consent: true
  
  repo-url: https://github.com/melsiddieg/moblog
  repo-actions: [edit, issue]
  page-navigation: true
  
  open-graph: 
    image: profile.jpg
  twitter-card: 
    image: profile.jpg
  favicon: profile.jpg

  google-analytics: "G-7QH7J2JLYY"
  
  page-footer:
    left: "Copyright 2025, Mohammed Abdallah"
    right: "Powered by [Quarto](https://quarto.org)"

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/melsiddieg
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    theme:
      dark: [slate, custom.scss]
      light: [cosmo, custom.scss]
      
    css: styles.css

editor: visual

  
