project:
  type: website
  output-dir: docs

website:
  title: "mofeed.xyz"
  google-analytics: "G-7QH7J2JLYY"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/melsiddieg
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    theme:
      dark: darkly
      light: lumen
      
    css: styles.css

editor: visual

  
